// Sample data derived from APX06142014.csv (Arlington Park, June 14 2014, Race 1)
// 1 1/16 miles, All-Weather, Maiden Special Weight, $34,000 purse

import type { RaceInfo } from "@/types/racing"

export const sampleRace: RaceInfo = {
  track: "AP",
  date: "June 14, 2014",
  raceNumber: 1,
  distance: 1870,
  surface: "AW",
  raceType: "Maiden Special Weight",
  purse: 34000,
  conditions: "FOR MAIDENS, THREE YEARS OLD AND UPWARD. Three Year Olds, 120 lbs.; Older, 124 lbs.",
  horses: [
    {
      name: "LARGE SCALE",
      programNumber: "1",
      postPosition: 1,
      sex: "H",
      color: "B",
      age: 5,
      sire: "PERFECT SOUL",
      dam: "GO FOR BAIL",
      damSire: "GO FOR GIN",
      owner: "Anne Wrenn Poulson Trust",
      trainer: "Reznikov Alexander",
      jockey: "Vashchenko Pavel",
      weightLbs: 124,
      morningLine: 1.8,
      lifetime:     { starts: 11, wins: 0, places: 3, shows: 3, earnings: 41875 },
      currentYear:  { starts:  5, wins: 0, places: 2, shows: 1, earnings: 24560 },
      previousYear: { starts:  6, wins: 0, places: 1, shows: 2, earnings: 17315 },
      pastStarts: [
        {
          date: "05/30/14", track: "AP", distance: 1760, surface: "AW",
          raceType: "MdSpWt", purse: 36000, finish: 3,
          speedFigure: 91, earlyPaceFigure: 82, latePaceFigure: 85,
          fractions: { time1: 24.08, time2: 48.22, final: 72.44 },
          positions: { start: 3, first: 3, second: 2, stretch: 2, finish: 3 },
          jockey: "Vashchenko P", weight: 124,
          comment: "Forwardly placed; chased inside; no match",
        },
        {
          date: "05/09/14", track: "AP", distance: 1760, surface: "AW",
          raceType: "MdSpWt", purse: 36000, finish: 2,
          speedFigure: 90, earlyPaceFigure: 81, latePaceFigure: 84,
          fractions: { time1: 26.49, time2: 50.77, final: 76.45 },
          positions: { start: 2, first: 2, second: 2, stretch: 2, finish: 2 },
          jockey: "Vashchenko P", weight: 124,
          comment: "Tracked inside; no kick",
        },
        {
          date: "04/18/14", track: "AP", distance: 2200, surface: "AW",
          raceType: "MdSpWt", purse: 36000, finish: 1,
          speedFigure: 94, earlyPaceFigure: 92, latePaceFigure: 88,
          fractions: { time1: 24.78, time2: 49.94, final: 75.77 },
          positions: { start: 1, first: 1, second: 1, stretch: 1, finish: 1 },
          jockey: "Vashchenko P", weight: 124,
          comment: "Pressed early; took over; long lead far turn; faltered stretch",
        },
        {
          date: "03/27/14", track: "AP", distance: 1320, surface: "AW",
          raceType: "MdSpWt", purse: 36000, finish: 4,
          speedFigure: 88,
          fractions: { time1: 26.17, time2: 50.21, final: 75.41 },
          positions: { start: 5, first: 4, second: 4, stretch: 4, finish: 4 },
          jockey: "Vashchenko P", weight: 124,
          comment: "Hustled early; 3w 1st turn; settled; 2path 2nd turn; 4w 1/4; no kick",
        },
        {
          date: "01/04/14", track: "KEE", distance: 2200, surface: "AW",
          raceType: "MdSpWt", purse: 58000, finish: 5,
          speedFigure: 71,
          fractions: { time1: 25.03, time2: 49.27, final: 74.38 },
          positions: { start: 3, first: 4, second: 5, stretch: 5, finish: 5 },
          jockey: "Vashchenko P", weight: 124,
          comment: "3w 1st turn; tracked outside; chased 2nd turn; tired",
        },
        {
          date: "12/12/13", track: "FG", distance: 2200, surface: "AW",
          raceType: "MdSpWt", purse: 41000, finish: 6,
          speedFigure: 77,
          fractions: { time1: 24.75, time2: 48.97, final: 75.13 },
          positions: { start: 8, first: 7, second: 7, stretch: 6, finish: 6 },
          jockey: "Vashchenko P", weight: 124,
          comment: "Last away; 3w 1st turn; jostled 5-1/2; moved out; 5w 1/4; weakened",
        },
        {
          date: "09/25/13", track: "FG", distance: 1320, surface: "AW",
          raceType: "MdSpWt", purse: 45000, finish: 3,
          speedFigure: 84,
          fractions: { time1: 25.56, time2: 48.18, final: 73.81 },
          positions: { start: 5, first: 5, second: 5, stretch: 4, finish: 3 },
          jockey: "Vashchenko P", weight: 124,
          comment: "Striking distance; 4 wide; lacked late bid",
        },
        {
          date: "08/18/13", track: "FG", distance: 1760, surface: "AW",
          raceType: "MdSpWt", purse: 45000, finish: 2,
          speedFigure: 79,
          fractions: { time1: 24.0, time2: 48.17, final: 73.07 },
          positions: { start: 3, first: 3, second: 3, stretch: 3, finish: 2 },
          jockey: "Vashchenko P", weight: 124,
          comment: "Tracked off 1st flight; switched out; bid 3-wide between; resisted",
        },
        {
          date: "07/21/13", track: "FG", distance: 1760, surface: "AW",
          raceType: "MdSpWt", purse: 45000, finish: 4,
          speedFigure: 65,
          fractions: { time1: 24.2, time2: 48.74, final: 74.1 },
          positions: { start: 4, first: 4, second: 4, stretch: 4, finish: 4 },
          jockey: "Vashchenko P", weight: 124,
          comment: "Tracked off 1st flight; steady bid into far turn; flattened out",
        },
        {
          date: "05/29/13", track: "AP", distance: 1320, surface: "AW",
          raceType: "MdSpWt", purse: 38000, finish: 7,
          speedFigure: undefined,
          fractions: { time1: 23.5, time2: 45.71, final: 71.81 },
          positions: { start: 9, first: 9, second: 9, stretch: 7, finish: 7 },
          jockey: "Hill C", weight: 124,
          comment: "Reserved widest early; never gained contention",
        },
      ],
      workouts: [
        { date: "06/09/14", track: "AP", distance: 660, time: "49.4", mark: "B", rank: "1/6" },
        { date: "06/02/14", track: "AP", distance: 1320, time: "1:13.0", mark: "", rank: "3/8" },
        { date: "05/26/14", track: "AP", distance: 660, time: "48.4", mark: "H", rank: "2/5" },
      ],
    },
    {
      name: "ROOLYNN RULER",
      programNumber: "2",
      postPosition: 2,
      sex: "G",
      color: "CH",
      age: 5,
      sire: "WESTERN OUTLAW",
      dam: "ROOLYNN",
      damSire: "RUHLMANN",
      owner: "JB Stables Inc",
      trainer: "Rose Heidi",
      jockey: "Perez Manny",
      weightLbs: 117,
      morningLine: 20,
      lifetime:     { starts: 13, wins: 0, places: 0, shows: 5, earnings: 5650 },
      currentYear:  { starts:  9, wins: 0, places: 0, shows: 2, earnings: 5550 },
      previousYear: { starts:  1, wins: 0, places: 0, shows: 0, earnings: 100 },
      pastStarts: [
        {
          date: "06/07/14", track: "AP", distance: 1760, surface: "D",
          raceType: "sMdSpWt", finish: 9,
          speedFigure: 57,
          fractions: { time1: 23.78, time2: 48.19, final: 73.68 },
          positions: { start: 1, first: 1, second: 1, stretch: 1, finish: 9 },
          jockey: "Perez M", weight: 119,
          comment: "Pace; clear; gave way",
        },
        {
          date: "05/18/14", track: "AP", distance: 1760, surface: "D",
          raceType: "sMdSpWt", finish: 8,
          speedFigure: 71,
          fractions: { time1: 24.23, time2: 48.37, final: 74.37 },
          positions: { start: 3, first: 3, second: 3, stretch: 3, finish: 8 },
          jockey: "Perez M", weight: 119,
          comment: "Btw for 6F; no bid",
        },
        {
          date: "05/08/14", track: "AP", distance: 1320, surface: "D",
          raceType: "Md12500", finish: 5,
          speedFigure: 83,
          fractions: { time1: 22.99, time2: 46.44, final: 58.62 },
          positions: { start: 4, first: 4, second: 3, stretch: 3, finish: 5 },
          jockey: "Perez M", weight: 119,
          comment: "Tracked leaders inside; shifted 3-wide lane; evenly late",
        },
        {
          date: "04/27/14", track: "HAW", distance: 1760, surface: "D",
          raceType: "Md8000", finish: 7,
          speedFigure: 83,
          fractions: { time1: 23.92, time2: 48.93, final: 75.38 },
          positions: { start: 6, first: 6, second: 7, stretch: 7, finish: 7 },
          jockey: "Perez M", weight: 119,
          comment: "Caught 6-wide early; early move 4-wide; no final kick",
        },
        {
          date: "04/13/14", track: "HAW", distance: 1760, surface: "D",
          raceType: "Md8000", finish: 6,
          speedFigure: 75,
          fractions: { time1: 25.14, time2: 51.2, final: 77.93 },
          positions: { start: 5, first: 5, second: 5, stretch: 6, finish: 6 },
          jockey: "Perez M", weight: 119,
          comment: "Hopped start; rated inside; bothered 3/16; late stride 5-wide",
        },
        {
          date: "04/02/14", track: "HAW", distance: 2200, surface: "D",
          raceType: "Md8000", finish: 1,
          speedFigure: 86,
          fractions: { time1: 24.62, time2: 50.21, final: 77.53 },
          positions: { start: 1, first: 1, second: 1, stretch: 1, finish: 1 },
          jockey: "Perez M", weight: 124,
          comment: "Urged clear inside; set pace into far turn; gave way nearing lane",
        },
        {
          date: "03/23/14", track: "HAW", distance: 2200, surface: "D",
          raceType: "Md8000", finish: 6,
          speedFigure: 75,
          fractions: { time1: 23.76, time2: 48.45, final: 74.89 },
          positions: { start: 7, first: 7, second: 6, stretch: 6, finish: 6 },
          jockey: "Perez M", weight: 118,
          comment: "Tracked off 2nd flight; caught 4-wide turn; dropped out",
        },
        {
          date: "03/05/14", track: "HAW", distance: 1760, surface: "D",
          raceType: "Md8000", finish: 8,
          speedFigure: 76,
          fractions: { time1: 22.73, time2: 46.6, final: 59.08 },
          positions: { start: 5, first: 5, second: 5, stretch: 8, finish: 8 },
          jockey: "Salgado M", weight: 124,
          comment: "Brief factor between foes 2nd flight; retreated early",
        },
      ],
      workouts: [
        { date: "06/07/14", track: "AP", distance: 660, time: "51.8", mark: "", rank: "5/7" },
        { date: "05/31/14", track: "AP", distance: 880, time: "1:03.2", mark: "", rank: "3/5" },
      ],
    },
    {
      name: "SILENT RULER",
      programNumber: "4",
      postPosition: 4,
      sex: "C",
      color: "DK B/BR",
      age: 4,
      sire: "ROMAN RULER",
      dam: "THEME SONG",
      damSire: "DIXIELAND BAND",
      owner: "Big Chief Thoroughbreds LLC",
      trainer: "Desormeaux J Keith",
      jockey: "Russell Sheldon",
      weightLbs: 120,
      morningLine: 4,
      lifetime:     { starts: 9, wins: 0, places: 2, shows: 3, earnings: 28810 },
      currentYear:  { starts: 5, wins: 0, places: 1, shows: 2, earnings: 15600 },
      previousYear: { starts: 4, wins: 0, places: 1, shows: 1, earnings: 13210 },
      pastStarts: [
        {
          date: "05/24/14", track: "AP", distance: 1760, surface: "AW",
          raceType: "MdSpWt", finish: 5,
          speedFigure: 80,
          fractions: { time1: 24.08, time2: 48.22, final: 72.44 },
          positions: { start: 5, first: 5, second: 5, stretch: 5, finish: 5 },
          jockey: "Desormeaux K J", weight: 118,
          comment: "Settled; off inside; 3-4 path lane",
        },
        {
          date: "04/26/14", track: "CD", distance: 1870, surface: "D",
          raceType: "Md50000", finish: 8,
          speedFigure: 69,
          fractions: { time1: 24.56, time2: 49.34, final: 74.64 },
          positions: { start: 8, first: 7, second: 7, stretch: 8, finish: 8 },
          jockey: "Desormeaux K J", weight: 125,
          comment: "Bumped early; trailed; 5 path far turn; moved up stretch",
        },
        {
          date: "12/13/13", track: "FG", distance: 2200, surface: "D",
          raceType: "MdSpWt", finish: 3,
          speedFigure: 75,
          fractions: { time1: 23.35, time2: 47.96, final: 75.18 },
          positions: { start: 3, first: 3, second: 3, stretch: 3, finish: 3 },
          jockey: "Napravnik A R", weight: 120,
          comment: "Settled; advanced 2nd turn; 4w 5/16; 5w 1/4; bid 3/16; came in 1/8; clear",
        },
        {
          date: "10/31/13", track: "SA", distance: 1870, surface: "D",
          raceType: "MdSpWt", finish: 2,
          speedFigure: 77,
          fractions: { time1: 23.23, time2: 47.31, final: 71.83 },
          positions: { start: 5, first: 5, second: 5, stretch: 4, finish: 2 },
          jockey: "Espinoza V", weight: 122,
          comment: "Unhurried early; off rail; outside; 3wd into lane; bested rest",
        },
        {
          date: "10/04/13", track: "SA", distance: 1430, surface: "D",
          raceType: "Md50000", finish: 3,
          speedFigure: 84,
          fractions: { time1: 22.2, time2: 45.38, final: undefined },
          positions: { start: 6, first: 6, second: 6, stretch: 6, finish: 3 },
          jockey: "Espinoza V", weight: 122,
          comment: "Off bit slow; settled; off rail; angled in 1/2; 4wd into lane; rallied",
        },
        {
          date: "08/09/13", track: "DMR", distance: 1320, surface: "D",
          raceType: "Md40000", finish: 6,
          speedFigure: 82,
          fractions: { time1: 22.52, time2: 45.89, final: undefined },
          positions: { start: 5, first: 5, second: 5, stretch: 6, finish: 6 },
          jockey: "Blanc B", weight: 120,
          comment: "Unhurried early; off rail; 3 wide turn and into lane; no rally",
        },
      ],
      workouts: [
        { date: "06/08/14", track: "AP", distance: 880, time: "1:00.4", mark: "H", rank: "2/8" },
        { date: "06/01/14", track: "AP", distance: 660, time: "49.8", mark: "", rank: "4/9" },
        { date: "05/24/14", track: "AP", distance: 880, time: "1:01.2", mark: "", rank: "5/11" },
      ],
    },
  ],
}
